export class BeersData{
    static data =[{
        "productName":"Pacific Pilsner",
        "productCode":"B01",
        "category":"beer",
        "flavor":"Dịu vị mật ong và ngũ cốc cùng da vị, thảo mộc sau khi uống",
        "odour":"",
        "color":"Vàng nhạt",
        "abv":"5%",
        "ibu":"25",
        "tags":"",
        "availableDate":"",
        "price":"57000",
        "pricesix":"308000",
        "priceten":"470000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"East West Pale",
        "productCode":"B02",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"6%",
        "ibu":"32",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Far East IPA",
        "productCode":"B03",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"6.7%",
        "ibu":"54",
        "tags":"",
        "availableDate":"",
        "price":"63000",
        "pricesix":"340000",
        "priceten":"515000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Saigon Rose",
        "productCode":"B04",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"3%",
        "ibu":"12",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Snow White",
        "productCode":"B05",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"4.5%",
        "ibu":"12-15",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"The Red Prince",
        "productCode":"B06",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"5%",
        "ibu":"10-15",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Mulberry Mermaid",
        "productCode":"B07",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"5%",
        "ibu":"10-15",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Belle Passion Fruit",
        "productCode":"B08",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"5%",
        "ibu":"15-18",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Plantinum Golden Ale",
        "productCode":"B09",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"4.6%",
        "ibu":"23",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Strongbow Gold",
        "productCode":"B10",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"4",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"36000",
        "pricesix":"195000",
        "priceten":"315000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Sài Gòn Special",
        "productCode":"B11",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"21000",
        "pricesix":"113000",
        "priceten":"183000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Heineken Bạc",
        "productCode":"B12",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"35000",
        "pricesix":"189000",
        "priceten":"305000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Tiger Nâu",
        "productCode":"B13",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"25000",
        "pricesix":"138000",
        "priceten":"220000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Tiger Bạc",
        "productCode":"B14",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"28000",
        "pricesix":"151000",
        "priceten":"245000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Budweiser",
        "productCode":"B15",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"37000",
        "pricesix":"199000",
        "priceten":"325000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
      "productName":"Kumlmbacher Export (330ml) ",
      "productCode":"B16",
      "category":"beer",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"5.4%",
      "ibu":"23",
      "tags":"",
      "availableDate":"",
      "price":"57000",
      "pricesix":"308000",
      "priceten":"470000",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10", "cost": ""
   },
   {
      "productName":"Kumlmbacher Edelherb (500ml)",
      "productCode":"B17",
      "category":"beer",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"5.4%",
      "ibu":"23",
      "tags":"",
      "availableDate":"",
      "price":"63000",
      "pricesix":"340000",
      "priceten":"515000",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10", "cost": ""
   },
   {
      "productName":"Monchshof Kellerbier",
      "productCode":"B18",
      "category":"beer",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"5.4%",
      "ibu":"23",
      "tags":"",
      "availableDate":"",
      "price":"89000",
      "pricesix":"0",
      "priceten":"0",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10", "cost": ""
   },

   {
      "productName":"Leffe Blonde",
      "productCode":"B19",
      "category":"beer",
      "flavor":"","odour":"","color":"","abv":"6.6%","ibu":"","tags":"Bỉ","availableDate":"",
      "price":"60000",
      "pricesix":"0","priceten":"0","description":"","starRating":"","imageUrl":"",
      "inventory":"10", 
      "cost": "31300"
   },

   {
      "productName":"Leffe Brune",
      "productCode":"B20",
      "category":"beer",
      "flavor":"","odour":"","color":"","abv":"6.5%","ibu":"","tags":"","availableDate":"",
      "price":"61000",
      "pricesix":"0","priceten":"0","description":"","starRating":"","imageUrl":"",
      "inventory":"10", 
      "cost": "35400"
   },   
   {
      "productName":"Hoegaarden Rosee",
      "productCode":"B21",
      "category":"beer",
      "flavor":"","odour":"","color":"","abv":"3%","ibu":"","tags":"","availableDate":"",
      "price":"57000",
      "pricesix":"0","priceten":"0","description":"","starRating":"","imageUrl":"",
      "inventory":"10", 
      "cost": "27100"
   },
   
   {
      "productName":"Hoegaarden",
      "productCode":"B22",
      "category":"beer",
      "flavor":"","odour":"","color":"","abv":"4.9%","ibu":"","tags":"","availableDate":"",
      "price":"57000",
      "pricesix":"0","priceten":"0","description":"","starRating":"","imageUrl":"",
      "inventory":"10", 
      "cost": "27100"
   },
   {
      "productName":"Stella Astois",
      "productCode":"B23",
      "category":"beer",
      "flavor":"","odour":"","color":"","abv":"5%","ibu":"","tags":"","availableDate":"",
      "price":"59000",
      "pricesix":"0","priceten":"0","description":"","starRating":"","imageUrl":"",
      "inventory":"10", 
      "cost": "32900"
   },
   {
      "productName":"Corona Extra",
      "productCode":"B24",
      "category":"beer",
      "abv":"4.6%",
      "cost": "27100",
      "price":"45000",
      "flavor":"","odour":"","color":"","ibu":"","tags":"","availableDate":"",      
      "pricesix":"0","priceten":"0","description":"","starRating":"","imageUrl":"",
      "inventory":"10", 
   },
   {
      "productName":"Kaiserdom Kellerbier",
      "productCode":"B25",
      "category":"beer",
      "abv":"4.7%",
      "cost": "28800",
      "price":"55000",
      "flavor":"","odour":"","color":"","ibu":"","tags":"","availableDate":"",      
      "pricesix":"0","priceten":"0","description":"","starRating":"","imageUrl":"",
      "inventory":"10", 
   },
   {
      "productName":"Kaiserdom Dark Lager",
      "productCode":"B26",
      "category":"beer",
      "abv":"4.7%",
      "cost": "28800",
      "price":"55000",
      "flavor":"","odour":"","color":"","ibu":"","tags":"","availableDate":"",      
      "pricesix":"0","priceten":"0","description":"","starRating":"","imageUrl":"",
      "inventory":"10", 
   },

   {
      "productName":"Chang",
      "productCode":"B27",
      "category":"beer",
      "abv":"5%",
      "cost": "18800",
      "price":"34000",
      "flavor":"","odour":"","color":"","ibu":"","tags":"","availableDate":"",      
      "pricesix":"0","priceten":"0","description":"","starRating":"","imageUrl":"",
      "inventory":"10", 
   },
   {
      "productName":"U",
      "productCode":"B28",
      "category":"beer",
      "abv":"5%",
      "cost": "24400",
      "price":"37000",
      "flavor":"","odour":"","color":"","ibu":"","tags":"","availableDate":"",      
      "pricesix":"0","priceten":"0","description":"","starRating":"","imageUrl":"",
      "inventory":"10", 
   },      
     {
        "productName":"Strongbow Red Berries",
        "productCode":"J01",
        "category":"juice",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"36000",
        "pricesix":"195000",
        "priceten":"315000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Strongbow Gold",
        "productCode":"J02",
        "category":"juice",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"36000",
        "pricesix":"195000",
        "priceten":"315000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Khô Bò",
        "productCode":"F01",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Khô Gà",
        "productCode":"F02",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Khô Cá",
        "productCode":"F03",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Khô Mực",
        "productCode":"F04",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Xúc xích chiên",
        "productCode":"F05",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Chả cá chiên",
        "productCode":"F06",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Chả cá hấp",
        "productCode":"F07",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Nem chua",
        "productCode":"F08",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", 
        "cost": ""
     },
     {
        "productName":"Chả lụa",
        "productCode":"F09",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Chả Quế",
        "productCode":"F10",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Chả giò",
        "productCode":"F11",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10",
        "cost":""
     },

     {
        "productName":"Chả Đặc biệt đủ loại",
        "productCode":"F12",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"89000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10",
        "cost":""
     },
     {
      "productName":"Thịt xông khói",
      "productCode":"F13",
      "category":"food",
      "price":"49000",
      "cost":"",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10"
   },
   {
      "productName":"Lạp xưởng",
      "productCode":"F14",
      "category":"food",
      "price":"49000",
      "cost":"",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10"
   },
   {
      "productName":"Phô mai",
      "productCode":"F15",
      "category":"food",
      "price":"49000",
      "cost":"",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10"
   },




     // cafe 
     {
      "productName":"Cafe đá",
      "productCode":"C01",
      "category":"coffee",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"18000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Cafe sữa đá",
      "productCode":"C02",
      "category":"coffee",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"21000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },  

   {
      "productName":"Nước suối",
      "productCode":"S01",
      "category":"soft",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"16000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"7Up",
      "productCode":"S02",
      "category":"soft",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"20000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Pepsi",
      "productCode":"S03",
      "category":"soft",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"20000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },
   {
      "productName":"Sting",
      "productCode":"S04",
      "category":"soft",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"20000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },
   {
      "productName":"Nước chanh",
      "productCode":"S05",
      "category":"soft",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"18000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },
   {
      "productName":"Bạc xỉu",
      "productCode":"C05",
      "category":"coffee",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"21000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Mixed Salad",
      "productCode":"O01",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"39000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Ceasar salad",
      "productCode":"O02",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"39000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Green Salad",
      "productCode":"O03",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"39000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Onion Ring",
      "productCode":"O04",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"39000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Xúc xích chiên sốt hành",
      "productCode":"O05",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"39000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },
   
   {
      "productName":"Phô mai que",
      "productCode":"O06",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"39000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Khoai tây chiên",
      "productCode":"O07",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"39000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Khoai tây nghiền chiên",
      "productCode":"O08",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"39000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Gà hun khói",
      "productCode":"O09",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Gà cuộn Bacon",
      "productCode":"O10",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Tôm cuộn Bacon",
      "productCode":"O11",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Fish and Chip",
      "productCode":"O12",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Bò lúc lắc khoai tây",
      "productCode":"O13",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Tôm rang muối HK",
      "productCode":"O14",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Tôm rang trứng muối",
      "productCode":"O15",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Chân gà rang muối HK",
      "productCode":"O16",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Cánh gà chiên nước mắm",
      "productCode":"O17",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Cánh gà chiên bơ",
      "productCode":"O18",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Chim cút chiên bơ",
      "productCode":"O19",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },
   {
      "productName":"Ếch chiên bơ",
      "productCode":"O20",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Đùi gà đút lò",
      "productCode":"O21",
      "category":"outside",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"59000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },
    ];
}