export class BeersData{
    static data =[{
        "productName":"Pacific Pilsner",
        "productCode":"B01",
        "category":"beer",
        "flavor":"Dịu vị mật ong và ngũ cốc cùng da vị, thảo mộc sau khi uống",
        "odour":"",
        "color":"Vàng nhạt",
        "abv":"5%",
        "ibu":"25",
        "tags":"",
        "availableDate":"",
        "price":"57000",
        "pricesix":"308000",
        "priceten":"470000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"East West Pale",
        "productCode":"B02",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"6%",
        "ibu":"32",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Far East IPA",
        "productCode":"B03",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"6.7%",
        "ibu":"54",
        "tags":"",
        "availableDate":"",
        "price":"63000",
        "pricesix":"340000",
        "priceten":"515000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Saigon Rose",
        "productCode":"B04",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"3%",
        "ibu":"12",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Snow White",
        "productCode":"B05",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"4.5%",
        "ibu":"12-15",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"The Red Prince",
        "productCode":"B06",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"5%",
        "ibu":"10-15",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Mulberry Mermaid",
        "productCode":"B07",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"5%",
        "ibu":"10-15",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Belle Passion Fruit",
        "productCode":"B08",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"5%",
        "ibu":"15-18",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Plantinum Golden Ale",
        "productCode":"B09",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"4.6%",
        "ibu":"23",
        "tags":"",
        "availableDate":"",
        "price":"59000",
        "pricesix":"318000",
        "priceten":"500000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Strongbow Gold",
        "productCode":"B10",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"4",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"36000",
        "pricesix":"195000",
        "priceten":"315000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Sài Gòn Special",
        "productCode":"B11",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"21000",
        "pricesix":"113000",
        "priceten":"183000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Heineken Bạc",
        "productCode":"B12",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"35000",
        "pricesix":"189000",
        "priceten":"305000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Tiger Nâu",
        "productCode":"B13",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"25000",
        "pricesix":"138000",
        "priceten":"220000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Tiger Bạc",
        "productCode":"B14",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"28000",
        "pricesix":"151000",
        "priceten":"245000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Budweiser",
        "productCode":"B15",
        "category":"beer",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"37000",
        "pricesix":"199000",
        "priceten":"325000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
      "productName":"Kumlmbacher Export (330ml) ",
      "productCode":"B16",
      "category":"beer",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"5.4%",
      "ibu":"23",
      "tags":"",
      "availableDate":"",
      "price":"57000",
      "pricesix":"308000",
      "priceten":"470000",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10", "cost": ""
   },
   {
      "productName":"Kumlmbacher Edelherb (500ml)",
      "productCode":"B17",
      "category":"beer",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"5.4%",
      "ibu":"23",
      "tags":"",
      "availableDate":"",
      "price":"63000",
      "pricesix":"340000",
      "priceten":"515000",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10", "cost": ""
   },
   {
      "productName":"Monchshof Kellerbier",
      "productCode":"B18",
      "category":"beer",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"5.4%",
      "ibu":"23",
      "tags":"",
      "availableDate":"",
      "price":"89000",
      "pricesix":"0",
      "priceten":"0",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10", "cost": ""
   },

     {
        "productName":"Strongbow Red Berries",
        "productCode":"J01",
        "category":"juice",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"36000",
        "pricesix":"195000",
        "priceten":"315000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Strongbow Gold",
        "productCode":"J02",
        "category":"juice",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"36000",
        "pricesix":"195000",
        "priceten":"315000",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Khô Bò",
        "productCode":"F01",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Khô Gà",
        "productCode":"F02",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Khô Cá",
        "productCode":"F03",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Khô Mực",
        "productCode":"F04",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Xúc xích chiên",
        "productCode":"F05",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Chả cá chiên",
        "productCode":"F06",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },

     {
        "productName":"Chả cá hấp",
        "productCode":"F07",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Nem chua",
        "productCode":"F08",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", 
        "cost": ""
     },
     {
        "productName":"Chả lụa",
        "productCode":"F09",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Chả Quế",
        "productCode":"F10",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10", "cost": ""
     },
     {
        "productName":"Chả giò",
        "productCode":"F11",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"49000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10",
        "cost":""
     },

     {
        "productName":"Chả Đặc biệt đủ loại",
        "productCode":"F12",
        "category":"food",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "price":"89000",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10",
        "cost":""
     },

     // cafe 
     {
      "productName":"Cafe đá",
      "productCode":"C01",
      "category":"coffee",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"18000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Cafe sữa đá",
      "productCode":"C02",
      "category":"coffee",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"21000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },  

   {
      "productName":"Nước suối",
      "productCode":"S01",
      "category":"soft",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"16000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"7Up",
      "productCode":"S02",
      "category":"soft",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"20000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },

   {
      "productName":"Pepsi",
      "productCode":"S03",
      "category":"soft",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"20000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },
   {
      "productName":"Sting",
      "productCode":"S04",
      "category":"soft",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"20000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },
   {
      "productName":"Nước chanh",
      "productCode":"S05",
      "category":"soft",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"18000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },
   {
      "productName":"Bạc xỉu",
      "productCode":"C05",
      "category":"coffee",
      "flavor":"",
      "odour":"",
      "color":"",
      "abv":"",
      "ibu":"",
      "tags":"",
      "availableDate":"",
      "price":"20000",
      "pricesix":"",
      "priceten":"",
      "description":"",
      "starRating":"",
      "imageUrl":"",
      "inventory":"10",
      "cost":""
   },
    ];
}