export class FoodData{
    static items =[
        {
            "productName":"Strongbow Red Berries",
            "productCode":"J01",
            "category":"juice",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"36000",
            "pricesix":"195000",
            "priceten":"315000",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", "cost": ""
        },

        {
            "productName":"Strongbow Gold",
            "productCode":"J02",
            "category":"juice",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"36000",
            "pricesix":"195000",
            "priceten":"315000",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", "cost": ""
        },

        {
            "productName":"Khô Bò",
            "productCode":"F01",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"49000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", "cost": ""
        },

        {
            "productName":"Khô Gà",
            "productCode":"F02",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"49000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", "cost": ""
        },

        {
            "productName":"Khô Cá",
            "productCode":"F03",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"49000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", "cost": ""
        },

        {
            "productName":"Khô Mực",
            "productCode":"F04",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"49000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", "cost": ""
        },
        {
            "productName":"Xúc xích chiên",
            "productCode":"F05",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"49000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", "cost": ""
        },
        {
            "productName":"Chả cá chiên",
            "productCode":"F06",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"49000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", "cost": ""
        },

        {
            "productName":"Chả cá hấp",
            "productCode":"F07",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"49000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", "cost": ""
        },
        {
            "productName":"Nem chua",
            "productCode":"F08",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"49000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", 
            "cost": ""
        },
        {
            "productName":"Chả lụa",
            "productCode":"F09",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"49000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", "cost": ""
        },
        {
            "productName":"Chả Quế",
            "productCode":"F10",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"49000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10", "cost": ""
        },
        {
            "productName":"Chả giò",
            "productCode":"F11",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"49000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10",
            "cost":""
        },

        {
            "productName":"Chả Đặc biệt đủ loại",
            "productCode":"F12",
            "category":"food",
            "flavor":"",
            "odour":"",
            "color":"",
            "abv":"",
            "ibu":"",
            "tags":"",
            "availableDate":"",
            "price":"89000",
            "pricesix":"",
            "priceten":"",
            "description":"",
            "starRating":"",
            "imageUrl":"",
            "inventory":"10",
            "cost":""
        },
        {
        "productName":"Thịt xông khói",
        "productCode":"F13",
        "category":"food",
        "price":"49000",
        "cost":"",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10"
        },
        {
        "productName":"Lạp xưởng",
        "productCode":"F14",
        "category":"food",
        "price":"49000",
        "cost":"",
        "flavor":"",
        "odour":"",
        "color":"",
        "abv":"",
        "ibu":"",
        "tags":"",
        "availableDate":"",
        "pricesix":"",
        "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10"
        },
        {
        "productName":"Phô mai",
        "productCode":"F15",
        "category":"food",
        "price":"49000",
        "cost":"",
        "flavor":"","odour":"","color":"","abv":"","ibu":"", "tags":"","availableDate":"", "pricesix":"", "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10"
        },

        {
        "productName":"Đậu phộng rang muối",
        "productCode":"F16",
        "category":"food",
        "price":"20000",
        "cost":"",
        "flavor":"","odour":"","color":"","abv":"","ibu":"", "tags":"","availableDate":"", "pricesix":"", "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10"
        },

        {
        "productName":"Nem chua",
        "productCode":"F17",
        "category":"food",
        "price":"49000",
        "cost":"",
        "flavor":"","odour":"","color":"","abv":"","ibu":"", "tags":"","availableDate":"", "pricesix":"", "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10"
        },
        {
        "productName":"Bò lá lốt",
        "productCode":"F18",
        "category":"food",
        "price":"49000",
        "cost":"",
        "flavor":"","odour":"","color":"","abv":"","ibu":"", "tags":"","availableDate":"", "pricesix":"", "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10"
        },

        {
        "productName":"Bánh mì ốp la xúc xích",
        "productCode":"F19",
        "category":"food",
        "price":"29000",
        "cost":"",
        "flavor":"","odour":"","color":"","abv":"","ibu":"", "tags":"","availableDate":"", "pricesix":"", "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10"
        },
        {
        "productName":"Chả tôm xay",
        "productCode":"F20",
        "category":"food",
        "price":"49000",
        "cost":"",
        "flavor":"","odour":"","color":"","abv":"","ibu":"", "tags":"","availableDate":"", "pricesix":"", "priceten":"",
        "description":"",
        "starRating":"",
        "imageUrl":"",
        "inventory":"10"
        }
    ]
}